version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "23:00"
      timezone: "UTC"
    groups:
      github-actions-major:
        patterns:
          - "*"
        update-types:
          - "major"
      github-actions-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "23:00"
      timezone: "UTC"
    groups:
      swift-major:
        patterns:
          - "*"
        update-types:
          - "major"
      swift-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
