default_platform(:ios)

platform :ios do
  desc "Build the Basic example app for PR validation"
  lane :build_basic do
    build_app(
      project: "Examples/Basic/Basic.xcodeproj",
      scheme: "Basic",
      configuration: "Debug",
      sdk: "iphonesimulator",
      destination: "generic/platform=iOS Simulator",
      clean: true,
      skip_archive: true,
      skip_package_ipa: true,
      skip_codesigning: true,
      xcargs: [
        "SWIFT_ENABLE_EXPERIMENTAL_PREBUILT=NO"
        ]
    )
  end
end


