name: Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Swift Package Tests
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Run unit tests
        run: swift test

  build-basic-example:
    name: Build Basic Example
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Build Basic example
        run: bundle exec fastlane build_basic

  build-basic-ios16-example:
    name: Build Basic iOS 16 Example
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Build Basic iOS 16 example
        run: bundle exec fastlane build_basic_ios16
