name: PR Validation

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Swift Package Tests
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Run unit tests
        run: swift test

  build-basic-example:
    name: Build Basic Example
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Build Basic example
        run: bundle exec fastlane build_basic
